# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/

stages:
    - build
    - test

build:ubuntu_latest:
    image: ubuntu:latest

    # Install dependencies
    before_script:
        - apt-get update &&
          apt-get upgrade -y &&
          apt-get install -y
            build-essential
            autotools-dev
            automake
            autoconf
            libtool
            pkg-config
            libboost-system-dev
            libboost-filesystem-dev
            libboost-program-options-dev
            libboost-thread-dev
            libboost-regex-dev
            libprotobuf-dev
            protobuf-compiler
            libprotobuf-c-dev
            protobuf-c-compiler
            libyaml-cpp-dev
            libyaml-dev
            libcap2-bin
            valgrind
          
    # Build and test
    script:
        - ./bootstrap.sh
        - mkdir build && cd build
        - ../configure 
            --enable-tests 
#            CFLAGS="-fsanitize=address"
#            CXXFLAGS="-fsanitize=address"
#            LDFLAGS="-fsanitize=address"
#            CPPFLAGS="-D__LOGGER_ENABLE_DEBUG__"
        - make -j4
        - cd tests
        - make -j4 api
        - whoami
        - NORNS_DEBUG_OUTPUT_TO_STDERR=1 NORNS_DEBUG_CONFIG_FILE_OVERRIDE=1 ./api
        - NORNS_DEBUG_CONFIG_FILE_OVERRIDE=1 ./api -as "[api::nornsctl_register_namespace]"
        - NORNS_DEBUG_CONFIG_FILE_OVERRIDE=1 ./api -as "[api::nornsctl_unregister_namespace]"
        - NORNS_DEBUG_CONFIG_FILE_OVERRIDE=1 ./api -as "[api::norns_submit_copy_local_posix_files]"
        - NORNS_DEBUG_CONFIG_FILE_OVERRIDE=1 ./api -as "[api::norns_submit_copy_buffer_to_file]"
        - NORNS_DEBUG_CONFIG_FILE_OVERRIDE=1 ./api -as "[api::nornsctl_register_job]"
        - NORNS_DEBUG_CONFIG_FILE_OVERRIDE=1 ./api -as "[api::nornsctl_update_job]"
        - NORNS_DEBUG_CONFIG_FILE_OVERRIDE=1 ./api -as "[api::nornsctl_unregister_job]"
        - NORNS_DEBUG_CONFIG_FILE_OVERRIDE=1 ./api -as "[api::nornsctl_ping]"
        - NORNS_DEBUG_CONFIG_FILE_OVERRIDE=1 ./api -as "[api::nornsctl_add_process]"
        - NORNS_DEBUG_CONFIG_FILE_OVERRIDE=1 ./api -as "[api::nornsctl_remove_process]"
        - NORNS_DEBUG_CONFIG_FILE_OVERRIDE=1 ./api -as "[api::norns_resource_init]"
        - NORNS_DEBUG_CONFIG_FILE_OVERRIDE=1 ./api -as "[api::norns_iotask_init]"
        - NORNS_DEBUG_CONFIG_FILE_OVERRIDE=1 ./api -as "[api::NORNS_TASK]"
##        - valgrind 
##            --leak-check=full 
##            -v 
##            env NORNS_DEBUG_CONFIG_FILE_OVERRIDE=1 
        - NORNS_DEBUG_CONFIG_FILE_OVERRIDE=1 ./api -as "[api::norns_submit]"
        - NORNS_DEBUG_CONFIG_FILE_OVERRIDE=1 ./api -as "[api::norns_status]"
        - NORNS_DEBUG_CONFIG_FILE_OVERRIDE=1 ./api -as "[api::nornsctl_status]"
    after_script:
        - pwd
        - if [[ -e tests.log ]]; 
          then
              cat $(tail -1 tests.log)/config/urd.log;
          fi

      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
